graph TD

A["<b>Phase 1: MakeCode/Minecraft</b><br><span style='font-size:2em;'>🎮</span><br><div style='text-align:left;'>- Motivation durch Spiele<br>- Medienkompetenz fördern</div>"] --> B;
B["<b>Phase 2: Python/Codingame</b><br><span style='font-size:2em;'>💻</span><br><div style='text-align:left;'>- Einstieg in Programmiersprachen<br>- Problemlösefähigkeit stärken</div>"] --> C;
C["<b>Phase 3: Hardware/Retro</b><br><span style='font-size:2em;'>🔌</span><br><div style='text-align:left;'>- Digitale Infrastruktur erleben<br>- Technisches Verständnis vertiefen</div>"] --> D;
D["<b>Phase 4: Daten & Gesellschaft</b><br><span style='font-size:2em;'>🌐</span><br><div style='text-align:left;'>- Datenschutz & Datenethik<br>- Gesellschaftlich relevante Themen</div>"] --> E;
E["<b>Phase 5: Cloud Computing</b><br><span style='font-size:2em;'>☁️</span><br><div style='text-align:left;'>- Cloud-Dienste verstehen<br>- Server & Skalierung praxisnah</div>"] --> F;
F["<b>Abschluss: Minecraft-Großprojekt</b><br><span style='font-size:2em;'>🎯</span><br><div style='text-align:left;'>- Projektlernen & Reflexion<br>- Präsentationskompetenz fördern</div>"];

style A fill:#ffe6c8,stroke:#bf7b31,stroke-width:2px
style B fill:#e4f2ff,stroke:#3066bf,stroke-width:2px
style C fill:#e5ffe5,stroke:#36ab54,stroke-width:2px
style D fill:#fff1f6,stroke:#b8266a,stroke-width:2px
style E fill:#f4f6ff,stroke:#465ac1,stroke-width:2px
style F fill:#f7f7f7,stroke:#232323,stroke-width:2px
